#!/bin/bash

set -e

curl localhost:3333/function/tempz/call -d "{\"env\": [{\"name\": \"AWS_ACCESS_KEY_ID\", \"value\": \"$AWS_ACCESS_KEY_ID\"}, {\"name\": \"AWS_SECRET_ACCESS_KEY\", \"value\": \"$AWS_SECRET_ACCESS_KEY\"}]}"
